In [1]:
import numpy as np

In [3]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [4]:
valoraciones[0][1]

7

In [5]:
valoraciones[0,1]

7

In [6]:
valoraciones[1,0]

2

In [10]:
valoraciones2 = np.array([[[8,7,8,5],[2,6,4,1]],[[8,8,9,3],[8,8,9,5]]])
valoraciones2

array([[[8, 7, 8, 5],
        [2, 6, 4, 1]],

       [[8, 8, 9, 3],
        [8, 8, 9, 5]]])

In [11]:
valoraciones2[0,1,2]

4

In [13]:
np.zeros((3,2,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [17]:
valoraciones2 + np.ones((2,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  7.,  5.,  2.]],

       [[ 9.,  9., 10.,  4.],
        [ 9.,  9., 10.,  6.]]])

In [19]:
m = np.mean(valoraciones2)
m

6.1875

In [21]:
np.mean(valoraciones2, axis = 0)

array([[8. , 7.5, 8.5, 4. ],
       [5. , 7. , 6.5, 3. ]])

In [22]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [23]:
np.median(df["Columna1"])

NameError: name 'df' is not defined

In [24]:
np.random.rand(2,2)

array([[0.64558338, 0.20075758],
       [0.17230586, 0.22436545]])